apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dice-roller
  description: It rolls dice
  tags:
    - go
  annotations:
    "backstage.io/kubernetes-id": dice-roller
    "backstage.io/kubernetes-label-selector": "someKey=someValue,other-key=other-value,app.kubernetes.io/name=dice-roller"
spec:
  type: service
  lifecycle: production
  owner: guest
